name: Deploy
run-name: Peanut Gallery UI Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v4
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: authenticate with aws
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::256470578440:role/PeanutGalleryGithubActionsUIDeployer
      - name: publish to s3
        run: aws s3 sync out s3://peanutgallery.taylorlaekeman.com
